### PR TITLE
Remove dependency on test.sh bash script to run the tests

### LINKED ISSUE #530: Remove dependency on test.sh bash script to run the tests
Currently this project relies on a script called `test.sh` to run the tests, which is a little unexpected. Usually Go projects will use the `go test` command to start the tests.

Looking at the `test.sh` script, it can set an environment variable for to run the tests for JSON or message pack then start running all the tests. Or it can run all the tests for both environment variables.

To reduce test flakiness, we now run tests for each protocol in its own Github runner (as running tests for both protocols in the same run was prone to test flakiness).

It would be possible to define the setting of environment variables as a step inside the pipeline with something like

```
  - name: Set env var for protocol
        run: echo "ABLY_PROTOCOL=${{ matrix.protocol }}" >> $GITHUB_ENV
```

Then inside the pipeline instead of running the `test.sh` the `go test` command could be used e.g. `go test -tags=integration -p 1 -race -v -timeout 120m ./...`

This would be a more readable, transparent way of running the tests in the pipeline and allow us to remove the dependency on a bash script which could then be deleted.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1932) by [Unito](https://www.unito.io)
┆sprint: SDK 2022-Q2-S5 26/05

### PR DESCRIPTION
**Pull request by Rosalita**
Resolves #530

### CODE REVIEW

File: scripts/test.sh [hunk 1]
```diff
@@ -1,61 +0,0 @@
-#!/usr/bin/env bash
-#
-# A script to run the tests.
```
Comment (sacOO7) [inline scripts/test.sh:3]: Actually, we were using this script to run all of the tests on the local, before checking them on CI. There are certain go test flags, which are easy to miss out otherwise while running tests.

File: .github/workflows/integration-test.yml [hunk 2]
```diff
@@ -30,10 +30,13 @@ jobs:
       - name: Install go-junit-report
         run: go install github.com/jstemmer/go-junit-report@latest
 
+      - name: Set env var for ablytest
+        run: echo "ABLY_PROTOCOL=${{ matrix.protocol == 'json' && 'application/json' || 'application/x-msgpack' }}" >> $GITHUB_ENV
```
Comment (lmars) [inline .github/workflows/integration-test.yml:34]: This could just be done within the script below rather than a separate step:

```yaml
run: |
  set -o pipefail
  export ABLY_PROTOCOL=${{ matrix.protocol == 'json' && 'application/json' || 'application/x-msgpack' }}
  go test -tags=integration ...

```

File: scripts/test.sh (hunk 1 above)
Comment (Rosalita) [reply scripts/test.sh:3]: Hi @sacOO7 please be aware that if you were using `test.sh` to run all the tests on this project, this would take twice as long to run all the tests as it now does to run them in CI (where they run in parallel as each suite has it's own runner).

The commands to run the test can always be copied directly from the pipeline's GitHub action .yml files. The project should not have to rely on a bash script when the pipeline can be expressed directly in the GitHub action .yml file. Please see #530 for more information and let me know if you still have any objection to the removal of this script.

File: .github/workflows/integration-test.yml [hunk 3]
```diff
@@ -29,11 +29,12 @@ jobs:
 
       - name: Install go-junit-report
         run: go install github.com/jstemmer/go-junit-report@latest
-
+
```
Comment (lmars) [inline .github/workflows/integration-test.yml:32]: This whitespace change isn't needed

**Review by lmars — APPROVED** [review]

File: .github/workflows/integration-test.yml (hunk 3 above)
Comment (Rosalita) [reply .github/workflows/integration-test.yml]: Looks like my IDE went rogue and put a tab in there. Removed now.

File: scripts/test.sh (hunk 1 above)
Comment (sacOO7) [reply scripts/test.sh:3]: `The commands to run the test can always be copied directly from the pipeline's GitHub action .yml files`. If we are planning to do this, can we update the `README` file for the same? I can see the `README` file section -> https://github.com/ably/ably-go#integration-tests still mentions the use of `scripts/test.sh`. Also, it will be great if we mention relevant flags as specified by the runner.

**Comment by Morganamilo** [comment]
I've wanted to do this for a while. The script is long and only has one line of value with some params change. The line can just be added to the readme if needed.

File: scripts/test.sh (hunk 1 above)
Comment (Rosalita) [reply scripts/test.sh:3]: Good spot with the readme file. I've just pushed an update to remove reference to `test.sh` and add the commands to run the tests.

Comment (sacOO7) [reply scripts/test.sh:3]: Nice work 👍

**Review by sacOO7 — APPROVED** [review]
LGTM
