### PR TITLE
Fix Request()

### LINKED ISSUE #486: AblyREST.Request() does not work
It looks like the paging for Request() doesn't actually save the results anywhere. So no matter what data is sent back calling `.Items()` on the results will always turn up empty.

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/SDK-1708) by [Unito](https://www.unito.io)
┆sprint: SDK 2022-Q2-S2 14/04

### PR DESCRIPTION
**Pull request by Morganamilo**
Fixes #486

### CODE REVIEW

File: ably/rest_client.go [hunk 1]
```diff
@@ -35,6 +36,23 @@ func query(fn func(context.Context, string, interface{}) (*http.Response, error)
 	}
 }
 
+type Raw []byte
```
Comment (Rosalita) [inline ably/rest_client.go:39]: As an exported type with exported methods, please can we add a comment line above the type to explain what this represents. Also a comment line above each exported method to explain their use. Main reason for adding this is to improve the auto generated docs at [pkg.go.dev](https://pkg.go.dev/github.com/ably/ably-go/ably)

Comment (Morganamilo) [reply ably/rest_client.go:39]: Actually I don't think this is meant to be exported whoops. Thanks.

File: ably/rest_client.go [hunk 2]
```diff
@@ -35,6 +36,23 @@ func query(fn func(context.Context, string, interface{}) (*http.Response, error)
...
+
+func (r *Raw) UnmarshalJSON(data []byte) error {
```
Comment (Rosalita) [inline ably/rest_client.go:41]: This function signature here can return an error, but I can see the code always returns nil. Is there some error handling missing here? Unmarshalling JSON is usually something that can go wrong and generate an error. How would that error be returned?

Comment (Morganamilo) [reply ably/rest_client.go:41]: The raw type just pretends to decode but returns the original bytes.

https://pkg.go.dev/encoding/json#RawMessage

Will be commented as  I forgot to comment Raw.

Comment (Rosalita) [reply ably/rest_client.go:41]: I see, so `Raw` has this method so that it can pass through the `Unmarshaler` interface.

File: ably/rest_client.go [hunk 3]
```diff
@@ -35,6 +36,23 @@ func query(fn func(context.Context, string, interface{}) (*http.Response, error)
...
+	*r = data
+	return nil
+}
+
+func (r *Raw) CodecEncodeSelf(*codec.Encoder) {
+	panic("Raw cannot be used as encoder")
```
Comment (Rosalita) [inline ably/rest_client.go:47]: I'm not sure the reason to use panic here. Panic will kill execution and cause an exit with a non-zero status, which feels a bit severe. Assuming this method is needed to satisfy an interface, is there a better way to handle the scenario when `CodecEncodeSelf` is called?

Comment (Morganamilo) [reply ably/rest_client.go:47]: This function will never be called. This is the same panic line taken from `rest_channel.go`

Comment (Rosalita) [reply ably/rest_client.go:47]: I don't like the `panic` there either, but at least we are being consistent :joy: 

Analysing our use of `panic` in this SDK is probably a bigger task for another day.

File: ably/rest_client.go [hunk 4]
```diff
@@ -470,12 +488,29 @@ func (p *HTTPPaginatedResponse) HasNext(ctx context.Context) bool {
...
+	/// Turn non arrays into arrays so it fits the output kind
+	if typ == "application/json" {
+		token, _ := json.NewDecoder(bytes.NewReader(p.items)).Token()
+		if token != json.Delim('[') {
+			p.items = append(Raw{'['}, p.items...)
+			p.items = append(p.items, ']')
+		}
+	} else if typ == "application/x-msgpack" {
+		if (p.items[0]&0xf0 != 0x90) && p.items[0] != 0xdc && p.items[0] != 0xdd {
+			p.items = append(Raw{0x91}, p.items...)
```
Comment (Rosalita) [inline ably/rest_client.go]: I'm having a hard time reading lines 509 and 510. Maybe some commenting is needed here?

`0x91` looks like a single left quote ( https://bytetool.web.app/en/ascii/code/0x91/ ) I'm not sure how appending this character converts the raw bytes to an array. Please can you talk me through these lines.

Comment (Morganamilo) [reply ably/rest_client.go]: messagepack is a binary format. The nibble 9 is used for the array type, followed by the length. So 91 is an array of length one.

File: ably/rest_client.go [hunk 5]
```diff
@@ -470,12 +490,29 @@ func (p *HTTPPaginatedResponse) HasNext(ctx context.Context) bool {
...
+
+	/// Turn non arrays into arrays so it fits the output kind
+	if typ == "application/json" {
+		token, _ := json.NewDecoder(bytes.NewReader(p.items)).Token()
+		if token != json.Delim('[') {
+			p.items = append(raw{'['}, p.items...)
+			p.items = append(p.items, ']')
+		}
+	} else if typ == "application/x-msgpack" {
+		if (p.items[0]&0xf0 != 0x90) && p.items[0] != 0xdc && p.items[0] != 0xdd {
```
Comment (Rosalita) [inline ably/rest_client.go:511]: Needs a comment for this if statement line, something like 
"Check the first byte to see if it's one of message packs three array types."

**Review by lmars — APPROVED** [review]
