### PR TITLE
Properly set  Error.StatusCode

### LINKED ISSUE #154: Lib failing to retrying on 5xx if it can't parse the body
[Customer using ably-go 1.1.2](https://support.ably.io/a/tickets/106111) reporting 400 errors. On investigation this was due to cloudfront returning rendered HTML for 502 errors; ably-go is then unable to parse the body, and turns it into a 400 error.

But this is incorrect - the library should be retrying for any response with an http status code 500-504 (specific spec violation: https://docs.ably.io/client-lib-development-guide/features/#RSC15d), doesn't matter what the body is. It still has the HTTP status code, and can decide to retry based on that.

Possibly introduced by https://github.com/ably/ably-go/pull/129/files (though that may have been fixing even-more-broken older behaviour)

### PR DESCRIPTION
**Pull request by gernest**
fixes #154

newError was completely ignoring  response status code.
It was wrongly deriving it from error code.

This patch ensures Error,StatusCode is set with correct response status.

### CODE REVIEW

File: ably/error_test.go [hunk 1]
```diff
@@ -54,3 +59,83 @@ func TestIssue127ErrorResponse(t *testing.T) {
 	assert.NotNil(t, err)
 	assert.Contains(t, err.Error(), errMsg)
 }
+
+func TestIssue_154(t *testing.T) {
```
Comment (tcard) [inline ably/error_test.go:63]: This tests a number of things that have nothing to do with #154. We just want to check that a HTTP response with 400 status code turns into an ErrorInfo with 400 status code.

There are other tests that test retries and fallbacks.

**Comment by gernest** [comment]
@tcard  PTAL  I added a simpler test where I only check to see the StatusCode is properly set in Error on not json/msgpack mime types.
